### ISSUE TITLE
Windows Anonio needs to be restarted daily.

### ISSUE THREAD

**Issue by jpass022** [anonymousbitcoin/anonio#1]
windows version of Anonio wallet changes from 'READY' to 'ERROR' on a daily basis... let me know if there's info needed to troubleshoot?  v7.0.2-rc1

**Comment by Skellers21** [comment]
Anonio has undergone significant updates recently and a new release is in the pipeline - this includes a completely new way to start and stop the embedded daemon which has certainly proved to be very reliable in testing

**Comment by jpass022** [comment]
will move to Anonio on Linux to see if more stable...
